### sql
DDL : 테이블을 생성, 변경, 제거  
    create : 테이블 생성 명령어
    alter  : 테이블 구조 변경 명령어
    drop   : 테이블 제거 명령어
DML : 테이블내에 저장된 데이터를 추가, 변경, 삭제, 조회 
    select(R) : 데이터 조회 명령어
    insert(C) : 데이터 추가 명령어
    update(U) : 데이터 변경 명령어
    delete(D) : 데이터 삭제 명령어

    CRUD : 데이터를 추가,조회,수정,삭제 용어

In [2]:
import sqlite3
dbpath="test.sqlite" #db 저장할 공간의 이름지정
# conn : sqlite 파일과 연결된 객체
conn = sqlite3.connect(dbpath) #db저장 공간 설정
cur = conn.cursor()
cur.execute("select * from items")
item_list = cur.fetchall() #실행된 결과를 리스트로 리턴
print(item_list)
print(type(item_list))

for item_id, name,price in item_list :
    print(item_id, name, price)

[(1, 'Apple', 800), (2, 'Orange', 500), (3, 'Banana', 600)]
<class 'list'>
1 Apple 800
2 Orange 500
3 Banana 600

In [5]:
# mydb sqlite db 생성하기
# mydb db에 usertable 테이블 생성하기
# id char(4) primary key, username char(15), email char(50),
#  birthyear int 컬럼을 가진 테이블 생성하기

import sqlite3
conn = sqlite3.connect("mydb")
cur = conn.cursor()
cur.executescript(
    '''
drop table if exists usertable;
create table usertable (
   id char(4) primary key,
   username char(15),
   email char(50),
   birthyear int
 );
    '''
)

In [7]:
#  화면에서 id, 이름, 이메일, 출생년도 입력받아 db에 등록하기
while True :
    d1 = input("사용자ID : ")
    if d1 == '' :
       break
    d2 = input("사용자이름 : ")
    d3 = input("이메일 : ")
    d4 = input("출생년도 : ")
    sql = "insert into usertable (id, username,email, birthyear) values ('" \
    +d1 + "','" + d2 +"','" + d3 + "'," + d4+")"
    print(sql)
    cur.execute(sql)
    conn.commit()
conn.close()

insert into usertable (id, username,email, birthyear) values ('t1','테스트1','t1@aaa.bbb',1990)
insert into usertable (id, username,email, birthyear) values ('t2','테스트2','t2@aaa.bbb',1993)

In [2]:
import sqlite3
conn = sqlite3.connect("mydb")
cur = conn.cursor()
cur.execute("select * from usertable")
userlist = cur.fetchall()
print(userlist)

[('t1', '테스트1', 't1@aaa.bbb', 1990), ('t2', '테스트2', 't2@aaa.bbb', 1993), ('t3', '테스트3', 't3@aaa.bbb', 1995), ('t4', '테스트4', 't4@aaa.bbb', 1998), ('t5', '테스트5', 'test5@aaa.bbb', 1992), ('t6', '테스트6', 'test6@aaa.bbb', 1993), ('t7', '테스트7', 'test7@aaa.bbb', 1993)]

In [9]:
#  화면에서 id, 이름, 이메일, 출생년도 입력받아 db에 등록하기
sql = "insert into usertable (id, username,email, birthyear) values (?,?,?,?)"
while True :
    d1 = input("사용자ID : ")
    if d1 == '' :
       break
    d2 = input("사용자이름 : ")
    d3 = input("이메일 : ")
    d4 = input("출생년도 : ")
    cur.execute(sql,(d1,d2,d3,d4))
    conn.commit()
conn.close()

In [18]:
conn.rollback()
conn.close()

In [ ]:
#여러개의 레코드 추가하기
import sqlite3
data = [('t5','테스트5','test5@aaa.bbb',1992),
        ('t6','테스트6','test6@aaa.bbb',1993),
        ('t7','테스트7','test7@aaa.bbb',1993)]
sql = "insert into usertable (id, username,email, birthyear) values (?,?,?,?)"
conn = sqlite3.connect("mydb")
cur = conn.cursor()
cur.executemany(sql,data) #여러건의 레코드 추가
conn.commit()

In [4]:
import sqlite3
conn = sqlite3.connect("mydb")
cur = conn.cursor()
cur.execute("select * from usertable")
userlist = cur.fetchall()
for row in userlist :
    print(row)

('t1', '테스트1', 't1@aaa.bbb', 1990)
('t2', '테스트2', 't2@aaa.bbb', 1993)
('t3', '테스트3', 't3@aaa.bbb', 1995)
('t4', '테스트4', 't4@aaa.bbb', 1998)
('t5', '테스트5', 'test5@aaa.bbb', 1992)
('t6', '테스트6', 'test6@aaa.bbb', 1993)
('t7', '테스트7', 'test7@aaa.bbb', 1993)

In [5]:
#데이터 수정하기
# t7인 레코드의 이메일:t7@aaa.bbb로 생년은 1999로 변경하기
cur = conn.cursor()
cur.execute("update usertable set email=?, birthyear=? where id=?",
            ('t7@aaa.bbb',1999,'t7'))
conn.commit()

In [6]:
import sqlite3
conn = sqlite3.connect("mydb")
cur = conn.cursor()
cur.execute("select * from usertable")
userlist = cur.fetchall()
for row in userlist :
    print(row)

('t1', '테스트1', 't1@aaa.bbb', 1990)
('t2', '테스트2', 't2@aaa.bbb', 1993)
('t3', '테스트3', 't3@aaa.bbb', 1995)
('t4', '테스트4', 't4@aaa.bbb', 1998)
('t5', '테스트5', 'test5@aaa.bbb', 1992)
('t6', '테스트6', 'test6@aaa.bbb', 1993)
('t7', '테스트7', 't7@aaa.bbb', 1999)

In [7]:
#t5 데이터 제거하기
cur = conn.cursor()
cur.execute("delete from usertable where id='t5'")
conn.commit()
conn.close()

In [8]:
import sqlite3
conn = sqlite3.connect("mydb")
cur = conn.cursor()
cur.execute("select * from usertable")
userlist = cur.fetchall()
for row in userlist :
    print(row)

('t1', '테스트1', 't1@aaa.bbb', 1990)
('t2', '테스트2', 't2@aaa.bbb', 1993)
('t3', '테스트3', 't3@aaa.bbb', 1995)
('t4', '테스트4', 't4@aaa.bbb', 1998)
('t6', '테스트6', 'test6@aaa.bbb', 1993)
('t7', '테스트7', 't7@aaa.bbb', 1999)

In [12]:
infp = open("test0911.py","r",encoding="UTF8")
while True :
    inStr = infp.readline() #한줄읽기
    if inStr == None or inStr == "" : #파일의 끝
        break
    print(inStr,end="")
infp.close()

# -*- coding: utf-8 -*-
'''
1.  화면에서 한개의 문자를 입력받아
     대문자인 경우는 소문자로,
     소문자인 경우는 대문자로
     숫자인 경우는 20을 더한 값을   출력하기
[예시]
한개의 문자를 입력하세요 : A
A 문자의 소문자는  a

한개의 문자를 입력하세요 : a
a 문자의 대문자는  A

한개의 문자를 입력하세요 : 1
1 + 20 = 21
'''

'''
2 (1)+(1+2)+(1+2+3)+(1+2+3+4)... (1+2+3+...10)=220 출력하기
'''


'''
3. 화면에서 자연수를 입력받아 각각의 자리수의 합을 구하기.

 [결과]
 자연수를 입력하세요 : 12345
 12345 자리수의 합: 15
'''


'''
4. aa,bb 리스트를 생성하고,
  aa 리스트는 0부터 짝수 100개를 저장하고
  bb 리스트는 aa 배열의 역순으로 값을 저장하기.
  aa[0] ~ aa[9], bb[99]~bb[90] 값을 출력하기
'''

'''
5. 다음 모레시계모양을 출력하기

모래시계의 높이를 홀수로 입력하세요 : 7
*******
 *****
  ***
   *
  ***
 *****
*******
'''

'''
6. 피보나치 수열 출력하기
   피보나치 수열은 0,1로 시작하고
   앞의 두수를 더하여 새로운 수를 만들어 주는 수열을 의미한다.
   피보나치 수열의 갯수를 입력받아 피보나치 수열을 갯수만큼 저장한
   리스트를 생성하는 함수 fibo 함수를 작성하기

0,1,1,2,3,5,8,13,21,34,55,89....
[결과]
피보나치 수열의 요소 갯수를 입력하세요(3이상의 값) :10
fibo( 10 )=[0, 1, 1, 2, 3, 5, 8, 13, 21, 34]
'''

In [ ]:
# 파일 저장하기. 
# 화면에서 입력받은 내용을 data.txt파일에 저장하기
outfp = open("data.txt","w",encoding="UTF8")
while True :
    outstr = input("내용 입력=>")
    if outstr == '' :  #입력중단
        break
    outfp.writelines(outstr+"\n")  #outfp 관리하는 파일에 내용을 쓰기
outfp.flush() #버퍼에 등록된 내용을 목적지(outfp) 전송.
outfp.close() #파일과 연결 종료
print("data.txt 파일 저장 완료")

data.txt 파일 저장 완료

In [ ]:
#data.txt 파일 읽기
infp = open("data.txt","r",encoding="UTF8")
while True :
    instr = infp.readline() #한줄씩 읽기
    if instr == None or instr == "" : #파일의 끝
        break
    print(instr,end="")
infp.close()

hello
안녕하세요
반갑습니다.
파일 쓰기 테스트 중입니다.
숫자 : 0123456789
영문:abcdefghi

In [ ]:
# readlines 함수를 이용하여 읽기. 
#   한줄씩 리스트로 반환
infp = open("data.txt","r",encoding="UTF8")
for str_line in infp.readlines() :
   print(str_line,end="")
infp.close()

In [ ]:
# read 함수를 이용하여 읽기. 
#   끝까지 한번에 읽기. 대용량 데이터 읽기에는 부적합
infp = open("data.txt","r",encoding="UTF8")
print(infp.read())
infp.close()

hello
안녕하세요
반갑습니다.
파일 쓰기 테스트 중입니다.
숫자 : 0123456789
영문:abcdefghi

In [20]:
#파일 정보 조회하기
import os.path
file = "data.txt"
file = "/Users/apple/temp"
if os.path.isfile(file) :
    print(file,"은 파일 입니다.")
if os.path.isdir(file) :
    print(file,"은 폴더입니다.")
if os.path.exists(file) :
    print(file,"은 존재합니다.")
else :
    print(file,"은 없습니다.")

/Users/apple/temp 은 없습니다.

In [ ]:
#작업폴더 조회하기
import os
print(os.getcwd())

/Users/apple/20260910

In [23]:
#현재폴더의 하위 파일 목록 조회하기
for f in os.listdir() :
    print(f)
#print(os.listdir())

mydb
python0915.ipynb
python0911.ipynb
.DS_Store
python0914.ipynb
pdf
mod1.py
__pycache__
python0910.ipynb
mod2.py
test0911-풀이.py
test0911.ipynb
test0911.py
test0914.ipynb
test.sqlite
.vscode
test0914.py
data.txt
test0910.py
test0910.ipynb

In [ ]:
#폴더 생성하기
os.mkdir("temp")

In [25]:
#폴더 제거하기
os.rmdir("temp")

In [27]:
'''
score.txt 파일의 내용
 홍길동,100
 김삿갓,50
 이몽룡,90
 임꺽정,80
 
 문제:score.txt 파일을 읽어서 점수의 총점과 평균 구하기
'''
import re
infp = open("score.txt","r",encoding="UTF8")
instr = infp.read()
pattern = re.compile(r"\d+")
list1 = re.findall(pattern,instr)
list1 = list(map(int, list1))
print("총점:",sum(list1),",  평균:", sum(list1)/len(list1))

총점: 320 ,  평균: 80.0

In [28]:
#2진파일을 읽어서 이진파일로 저장하기
#apple.gif 파일을 읽어서 apple2.gif 파일로 저장하기
#apple.gif 파일 읽기
infp = open("apple.gif","rb")
#apple2.gif 파일에 쓰기
outfp = open("apple2.gif","wb")
while True :
    indata = infp.read(8096) #8096바이트만큼 읽기
    if not indata :
        break
    outfp.write(indata)
infp.close()
outfp.flush()
outfp.close()

In [34]:
#with 구문 : 자동으로 close를 해주는 기능
#csv파일 읽기 : 텍스트파일. 단어간의 ,로 구분됨
#jeju1.csv 파일을 jeju2.csv로 저장하기
# 맥 : 기본 인코딩 UTF8
# 윈도우 : 기본 인코딩 CP949
with open('jeju1.csv','r',encoding="UTF8") as infp :
    with open("jeju2.csv","w",encoding="utf8") as outfp :
        header = infp.readline()
        print(header)
        header = header.strip()
        header_list = header.split(",") #["장소","LON","LAT"]
        outfp.write(",".join(map(str,header_list)) + "\r\n")
        for row in infp :  #infp 파일에서 한줄씩 데이터 읽기
            outfp.write(row)

장소,LON,LAT

### Pandas
pip3 install pandas => pandas 모듈 설치

In [ ]:
#dictionary를 이용하여 Series 데이터 생성하기
# dictionary의 키 부분이 index값임
import pandas as pd #pip3 install pandas
dict_data = {'a':1,'b':2,'c':3}
sr = pd.Series(dict_data)
print(type(sr))
print(sr)
print(sr.index) #[a,b,c]
print(sr.values) #[1,2,3]

<class 'pandas.Series'>
a    1
b    2
c    3
dtype: int64
Index(['a', 'b', 'c'], dtype='str')
[1 2 3]

In [37]:
#List 데이터를 Series 데이터로 생성
list_data = ['2026-09-15',3.14,'ABC',100,True]
sr = pd.Series(list_data)
print(sr)
print(sr.index)
print(sr.values)

0    2026-09-15
1          3.14
2           ABC
3           100
4          True
dtype: object
RangeIndex(start=0, stop=5, step=1)
['2026-09-15' 3.14 'ABC' 100 True]

In [40]:
tu_data = ('2026-09-15',3.14,'ABC',100,True)
sr = pd.Series(tu_data,index=["날짜","원주율","문자","숫자","논리값"])
print(sr)
print(sr.index)
print(sr.values)

날짜     2026-09-15
원주율          3.14
문자            ABC
숫자            100
논리값          True
dtype: object
Index(['날짜', '원주율', '문자', '숫자', '논리값'], dtype='str')
['2026-09-15' 3.14 'ABC' 100 True]

In [48]:
# Series 데이터 조회하기 . sr[인덱스명]
print(sr['날짜'])  #인덱스가 날짜인 데이터 조회
# 인덱스가 날짜, 원주율, 숫자 데이터 조회
print(sr[["날짜","원주율","숫자"]])

2026-09-15
날짜     2026-09-15
원주율          3.14
숫자            100
dtype: object

In [ ]:
# 범위 지정 데이터 조회 (원주율,문자)
print(sr.index)
print(sr["원주율":"문자"]) #인덱스 이름으로 조회
print(sr[1:3])          #인덱스 번호로 조회

Index(['날짜', '원주율', '문자', '숫자', '논리값'], dtype='str')
원주율    3.14
문자      ABC
dtype: object
원주율    3.14
문자      ABC
dtype: object

In [56]:
#원주율, 숫자 데이터 조회하기
print(sr[["원주율","숫자"]])

원주율    3.14
숫자      100
dtype: object

In [ ]:
# 데이터 프레임(DataFrame) 생성하기
dict_data = {'c0':[1,2,3],'c1':[4,5,6],'c2':[7,8,9],
             'c3':[10,11,12],'c4':[13,14,15]}
df = pd.DataFrame(dict_data)
print(type(df))
print(df)
print(df.index) # 행을 지정하는 이름
print(df.columns) #열을 지정하는 이름

<class 'pandas.DataFrame'>
   c0  c1  c2  c3  c4
0   1   4   7  10  13
1   2   5   8  11  14
2   3   6   9  12  15
RangeIndex(start=0, stop=3, step=1)
Index(['c0', 'c1', 'c2', 'c3', 'c4'], dtype='str')

In [60]:
sr = df["c0"]
print(type(sr))

<class 'pandas.Series'>

In [62]:
#리스트로 DataFrame 생성하기
df = pd.DataFrame([[15,'남','서울중'],[17,'여','서울고']],
                  index=["길동","길순"],columns=['나이','성별','학교'])
print(df)
print(df.index)
print(df.columns)

    나이 성별   학교
길동  15  남  서울중
길순  17  여  서울고
Index(['길동', '길순'], dtype='str')
Index(['나이', '성별', '학교'], dtype='str')

In [63]:
#컬럼명으로 조회하기 : 성별 조회하기
print(df["성별"])

길동    남
길순    여
Name: 성별, dtype: str

In [ ]:
#인덱스명으로 조회하기. 길동 조회하기
#loc : 인덱스명으로 조회
#iloc : 인덱스번호로 조회
print(df.loc["길동"])
print(df.iloc[0])

나이     15
성별      남
학교    서울중
Name: 길동, dtype: object
나이     15
성별      남
학교    서울중
Name: 길동, dtype: object

In [68]:
#인덱스명 변경하기
df.index = ['학생1','학생2']
print(df)
#컬럼명 변경하기
df.columns = ['연령','남녀','소속']
print(df)

     나이 성별   학교
학생1  15  남  서울중
학생2  17  여  서울고
     연령 남녀   소속
학생1  15  남  서울중
학생2  17  여  서울고

In [ ]:
#컬럼명 중 연령 => 나이 변경하기
# inplace=True : df 데이터를 변경하기.
# rename 함수의 결과는 자체 데이터를 변경하시 않음. 
df.rename(columns={'연령':'나이'},inplace=True)
print(df)
#인덱스 명을 학생1:홍길동, 학생2:홍길순 으로 변경하기
df = df.rename(index={"학생1":"홍길동","학생2":"홍길순"})
print(df)

     나이 남녀   소속
학생1  15  남  서울중
학생2  17  여  서울고
     나이 남녀   소속
홍길동  15  남  서울중
홍길순  17  여  서울고

In [75]:
#exam_data를 활용하여 인덱스는 홍길동, 이몽룡, 김삿갓으로 데이터 프레임 객체를 생성하기
exam_data = {'수학' : [ 90, 80, 70], '영어' : [ 98, 89, 95],
             '음악' : [ 85, 95, 100], '체육' : [ 100, 90, 90]}

df = pd.DataFrame(exam_data)
print(df)
df.index = ["홍길동","이몽룡","김삿갓"]
print(df)
df = pd.DataFrame(exam_data,index=["홍길동","이몽룡","김삿갓"])
print(df)

   수학  영어   음악   체육
0  90  98   85  100
1  80  89   95   90
2  70  95  100   90
     수학  영어   음악   체육
홍길동  90  98   85  100
이몽룡  80  89   95   90
김삿갓  70  95  100   90
     수학  영어   음악   체육
홍길동  90  98   85  100
이몽룡  80  89   95   90
김삿갓  70  95  100   90

In [76]:
#탐색적 분석
#데이터 전체의 구조 조회하기
df.info()

<class 'pandas.DataFrame'>
Index: 3 entries, 홍길동 to 김삿갓
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   수학      3 non-null      int64
 1   영어      3 non-null      int64
 2   음악      3 non-null      int64
 3   체육      3 non-null      int64
dtypes: int64(4)
memory usage: 120.0+ bytes

In [77]:
df.describe()

         수학         영어          음악          체육
count   3.0   3.000000    3.000000    3.000000
mean   80.0  94.000000   93.333333   93.333333
std    10.0   4.582576    7.637626    5.773503
min    70.0  89.000000   85.000000   90.000000
25%    75.0  92.000000   90.000000   90.000000
50%    80.0  95.000000   95.000000   90.000000
75%    85.0  96.500000   97.500000   95.000000
max    90.0  98.000000  100.000000  100.000000

In [81]:
#mean() : 평균출력
print(df.mean())

수학    80.000000
영어    94.000000
음악    93.333333
체육    93.333333
dtype: float64

In [82]:
# 수학 평균 출력하기
print(df["수학"].mean())
print(df.mean()["수학"])

80.0
80.0

In [85]:
#홍길동 학생의 평균 구하기
print(df.loc["홍길동"].mean())
print(df.iloc[0].mean())

93.25
93.25

In [ ]:
#median() : 중앙값. 홀수개인 데이터: 가운데값. 짝수개인데이터:가운데값2개의 평균
print(df.median())
print(df)
#수학의 중앙값 출력
print(df["수학"].median())
print(df.median()["수학"])
print(df.수학.median()) #df.수학 = df['수학']

수학    80.0
영어    95.0
음악    95.0
체육    90.0
dtype: float64
     수학  영어   음악   체육
홍길동  90  98   85  100
이몽룡  80  89   95   90
김삿갓  70  95  100   90
80.0
80.0
80.0

In [ ]:
#홍길동 학생의 중앙값. 짝수개이므로 가운데값의 평균
print(df.loc["홍길동"])
print(df.loc["홍길동"].median()) # 90+98 = 188/2 = 94

수학     90
영어     98
음악     85
체육    100
Name: 홍길동, dtype: int64
94.0

In [94]:
#max, min, std
print(df.max()) #과목별 최대값
print(df.min()) #과목별 최소값
print(df.std()) #과목별 표준편차
#홍길동 학생의 표준편차
print(df.loc["홍길동"].std())

수학     90
영어     98
음악    100
체육    100
dtype: int64
수학    70
영어    89
음악    85
체육    90
dtype: int64
수학    10.000000
영어     4.582576
음악     7.637626
체육     5.773503
dtype: float64
6.994045086119096

In [95]:
#corr () : 상관계수 : 두개의 변수들간의 관계. 
print(df.corr())

          수학        영어        음악        체육
수학  1.000000  0.327327 -0.981981  0.866025
영어  0.327327  1.000000 -0.500000  0.755929
음악 -0.981981 -0.500000  1.000000 -0.944911
체육  0.866025  0.755929 -0.944911  1.000000

In [97]:
# 수학, 영어의 상관계수 출력하기
print(df[["수학","영어"]].corr())

          수학        영어
수학  1.000000  0.327327
영어  0.327327  1.000000

In [ ]:
#데이터 프레임 복사하기
df2 = df #얕은복사, 이름만 추가, 객체는 한개임
print(df2)
print(df)
df2.index = ['a','b','c']
print(df2)
print(df)

     수학  영어   음악   체육
홍길동  90  98   85  100
이몽룡  80  89   95   90
김삿갓  70  95  100   90
     수학  영어   음악   체육
홍길동  90  98   85  100
이몽룡  80  89   95   90
김삿갓  70  95  100   90
   수학  영어   음악   체육
a  90  98   85  100
b  80  89   95   90
c  70  95  100   90
   수학  영어   음악   체육
a  90  98   85  100
b  80  89   95   90
c  70  95  100   90

In [101]:
#깊은 복사
df2 = df[:]
print(df2)
print(df)
df.index = ['홍길동','이몽룡','김삿갓']
print(df2)
print(df)

   수학  영어   음악   체육
a  90  98   85  100
b  80  89   95   90
c  70  95  100   90
   수학  영어   음악   체육
a  90  98   85  100
b  80  89   95   90
c  70  95  100   90
   수학  영어   음악   체육
a  90  98   85  100
b  80  89   95   90
c  70  95  100   90
     수학  영어   음악   체육
홍길동  90  98   85  100
이몽룡  80  89   95   90
김삿갓  70  95  100   90

In [102]:
print(df[:])

     수학  영어   음악   체육
홍길동  90  98   85  100
이몽룡  80  89   95   90
김삿갓  70  95  100   90

In [104]:
#df2 데이터에서 a 행을 제거하기
print(df2)
df2.drop("a",inplace=True)
print(df2)

   수학  영어   음악   체육
a  90  98   85  100
b  80  89   95   90
c  70  95  100   90
   수학  영어   음악  체육
b  80  89   95  90
c  70  95  100  90

In [ ]:
# df데이터를 복사하여 df3데이터를 생성하고, 홍길동,김삿갓 행을 제거하기
df3 = df[:]
df3.drop(["홍길동","김삿갓"],inplace=True, axis=0) #axis=0 : 행을 의미함
print(df3)

     수학  영어  음악  체육
이몽룡  80  89  95  90

In [109]:
# 체육 컬럼 제거하기
df4 = df.copy()
print(df4)
df4.drop("체육", inplace=True, axis=1)
print(df4)

     수학  영어   음악   체육
홍길동  90  98   85  100
이몽룡  80  89   95   90
김삿갓  70  95  100   90
     수학  영어   음악
홍길동  90  98   85
이몽룡  80  89   95
김삿갓  70  95  100

In [ ]:
# df5 데이터를 df 데이터로부터 복사하여, df5 음악과 체육 컬럼을 삭제하기
df5 = df.copy()
df5.drop(["음악","체육"],inplace=True, axis=1)
print(df5)

     수학  영어
홍길동  90  98
이몽룡  80  89
김삿갓  70  95

In [111]:
del df5["영어"]
print(df5)

     수학
홍길동  90
이몽룡  80
김삿갓  70

In [ ]:
df = pd.DataFrame(data=([[1,2,3],[4,5,6],[7,8,9]]),
                  index=[2,'A',4],columns=[51,52,54])
print(df)
df.info()

In [116]:
print(df.iloc[2]) #[7,8,9]
print(df.loc[2]) #[1,2,3]
#A인덱스의 데이터를 조회하기
print(df.loc['A'])
print(df.iloc[1])

51    7
52    8
54    9
Name: 4, dtype: int64
51    1
52    2
54    3
Name: 2, dtype: int64
51    4
52    5
54    6
Name: A, dtype: int64
51    4
52    5
54    6
Name: A, dtype: int64

In [ ]:
#인덱스이름 2,4인 행을 출력하기
print(df.loc[[2,4]])
print(df.iloc[[0,2]])
print(type(df.loc[[2,4]])) #DataFrame
print(type(df.loc[2]))  #Series

In [ ]:
#범위 지정하기
print(df.loc[2:'A'])
print(df.iloc[:2])

In [ ]:
print(df.loc[::2]) # df.loc[시작인덱스이름:종료인덱스이름:건너뛰기]
print(df.iloc[::2]) # df.iloc[시작인덱스번호:종료인덱스번호+1:건너뛰기]

   51  52  54
2   1   2   3
4   7   8   9
   51  52  54
2   1   2   3
4   7   8   9

In [125]:
print(df.loc[4])

51    7
52    8
54    9
Name: 4, dtype: int64

In [126]:
exam_data = {'이름' : [ '서준', '우현', '인아'],
             '수학' : [ 90, 80, 70],
             '영어' : [ 98, 89, 95],
             '음악' : [ 85, 95, 100],
             '체육' : [ 100, 90, 90]}
df = pd.DataFrame(exam_data)
df

   이름  수학  영어   음악   체육
0  서준  90  98   85  100
1  우현  80  89   95   90
2  인아  70  95  100   90

In [134]:
# 국어 컬럼 추가하기
df["국어"] = 80
df
#  서준:80, 우현:90, 인아:95 저장하기
df["국어"] = [80,90,95]
df
#서준의 국어 점수 출력하기
print(df.loc[df["이름"]=='서준'])
print(df.loc[df["이름"]=='서준','국어'])
print(df.loc[df['이름']=='서준']["국어"])

   이름  수학  영어  음악   체육  국어
0  서준  90  98  85  100  80
0    80
Name: 국어, dtype: int64
0    80
Name: 국어, dtype: int64

In [135]:
#행 추가하기
df.loc[3]=0
df

   이름  수학  영어   음악   체육  국어
0  서준  90  98   85  100  80
1  우현  80  89   95   90  90
2  인아  70  95  100   90  95
3   0   0   0    0    0   0

In [136]:
#인덱스값이 3인 레코드에 값을 길동, 75,80,90,95,85 추가하기
df.loc[3]=['길동',75,80,90,95,85]
df

   이름  수학  영어   음악   체육  국어
0  서준  90  98   85  100  80
1  우현  80  89   95   90  90
2  인아  70  95  100   90  95
3  길동  75  80   90   95  85

In [137]:
#
df.loc[5]=['길순',75,80,90,95,85]
df

   이름  수학  영어   음악   체육  국어
0  서준  90  98   85  100  80
1  우현  80  89   95   90  90
2  인아  70  95  100   90  95
3  길동  75  80   90   95  85
5  길순  75  80   90   95  85